sonar:
  image: sonarqube:latest
  ports:
   - "9000:9000"
   - "9092:9092"
nexus:
  image: sonatype/nexus:oss
  ports:
   - "8081:8081"
jenkins:
  image: pradeep/jenkins2-cf-pipeline-demo
  ports:
   - "8080:8080"
   - "50000:50000"
  volumes:
    - /var/jenkins_home
  links:
   - nexus
# gerrit:
#   container_name: gerrit
#   hostname: gerrit
#   build: ./gerrit
#   ports:
#     - "8080:8080"
#     - "29418:29418"
